import type { LiveHostApi } from '../shared/host-api.ts';

const INTERACTIVE_CONTROL =
  'button, input, select, textarea, a, summary, label, [contenteditable], [role="button"], [role="switch"], [data-live-no-drag]';

/** Drag a visible surface without turning its controls or transparent canvas into handles. */
export function makeOverlayDraggable(
  element: HTMLElement,
  api: Pick<LiveHostApi, 'dragOverlay'>,
): () => void {
  const document = element.ownerDocument;
  const window = document.defaultView!;
  element.dataset.liveDrag = '';
  let start: { x: number; y: number; id: number; target: Element } | undefined;
  let last = { x: 0, y: 0 };
  let dragging = false;
  let suppressClick = false;
  let clickOrigin: Element | undefined;
  let clickReset: ReturnType<typeof setTimeout> | undefined;
  const clearClick = () => {
    suppressClick = false;
    clickOrigin = undefined;
    if (clickReset !== undefined) clearTimeout(clickReset);
    clickReset = undefined;
  };
  const end = (event?: PointerEvent) => {
    if (!start || (event && event.pointerId !== start.id)) return;
    const id = start.id;
    const origin = start.target;
    start = undefined;
    if (dragging) {
      const position =
        event?.type === 'pointerup'
          ? { x: event.screenX, y: event.screenY }
          : last;
      api.dragOverlay('end', position.x, position.y);
      // Only swallow the click generated by this completed pointer gesture.
      // A lost capture or blur must never swallow a later real button click.
      if (event?.type === 'pointerup') {
        suppressClick = true;
        clickOrigin = origin;
        clickReset = setTimeout(clearClick, 0);
      }
    }
    dragging = false;
    if (element.hasPointerCapture?.(id)) element.releasePointerCapture(id);
  };
  const down = (event: PointerEvent) => {
    clearClick();
    if (start || event.button !== 0 || event.isPrimary === false) return;
    const target = event.target instanceof window.Element ? event.target : null;
    if (target?.closest(INTERACTIVE_CONTROL)) return;
    start = {
      x: event.screenX,
      y: event.screenY,
      id: event.pointerId,
      target: target ?? element,
    };
    last = { x: event.screenX, y: event.screenY };
    dragging = false;
    // Prevent native image dragging/text selection, but not the controls excluded above.
    event.preventDefault();
    try {
      element.setPointerCapture?.(event.pointerId);
    } catch {
      // Document listeners still complete gestures if capture is unavailable.
    }
  };
  const move = (event: PointerEvent) => {
    if (!start || event.pointerId !== start.id) return;
    if (event.pointerType === 'mouse' && event.buttons === 0) {
      end();
      return;
    }
    last = { x: event.screenX, y: event.screenY };
    if (
      !dragging &&
      Math.hypot(event.screenX - start.x, event.screenY - start.y) < 5
    )
      return;
    if (!dragging) {
      dragging = true;
      api.dragOverlay('start', start.x, start.y);
    }
    api.dragOverlay('move', event.screenX, event.screenY);
    event.preventDefault();
  };
  const click = (event: MouseEvent) => {
    if (!suppressClick) return;
    const isDragClick =
      event.target instanceof window.Node &&
      clickOrigin &&
      event.target.contains(clickOrigin);
    clearClick();
    if (!isDragClick) return;
    event.preventDefault();
    event.stopImmediatePropagation();
  };
  const blur = () => end();
  element.addEventListener('pointerdown', down);
  element.addEventListener('lostpointercapture', end);
  // Captured events bubble here; these also cover release outside the handle
  // when the browser cannot acquire capture. Native keeps the window interactive
  // from drag start through end, even while the pointer crosses transparent space.
  document.addEventListener('pointermove', move);
  document.addEventListener('pointerdown', clearClick, true);
  document.addEventListener('pointerup', end);
  document.addEventListener('pointercancel', end);
  document.addEventListener('click', click, true);
  window.addEventListener('blur', blur);
  return () => {
    end();
    clearClick();
    element.removeEventListener('pointerdown', down);
    element.removeEventListener('lostpointercapture', end);
    document.removeEventListener('pointermove', move);
    document.removeEventListener('pointerdown', clearClick, true);
    document.removeEventListener('pointerup', end);
    document.removeEventListener('pointercancel', end);
    document.removeEventListener('click', click, true);
    window.removeEventListener('blur', blur);
    delete element.dataset.liveDrag;
  };
}
