/**
 * @license
 * Copyright 2026 Qwen
 * SPDX-License-Identifier: Apache-2.0
 */

// Browser-safe contract shared by Host preparation and daemon admission.
export const VOICE_SAMPLE_RATE = 24_000;
export const VOICE_SAMPLE_MAX_SECONDS = 60;
export const VOICE_SAMPLE_MIN_SECONDS = 3;
export const VOICE_SAMPLE_MAX_BYTES =
  44 + VOICE_SAMPLE_RATE * 2 * VOICE_SAMPLE_MAX_SECONDS;
export const VOICE_CLONE_MAX_REQUEST_BYTES =
  Math.ceil(VOICE_SAMPLE_MAX_BYTES / 3) * 4 + 1024;
export const VOICE_CLONE_TIMEOUT_MS = 120_000;

export type VoiceSampleInfo = {
  name: string;
  seconds: number;
  previewUrl: string;
};
export type VoiceCloneOutcome =
  | { ok: true; voice: string; warning?: string }
  | { ok: false; error: string; createdVoice?: string };

export function parseVoiceCloneOutcome(
  value: unknown,
): VoiceCloneOutcome | undefined {
  if (!value || typeof value !== 'object') return undefined;
  const v = value as Record<string, unknown>;
  const id = (s: unknown): s is string =>
    typeof s === 'string' &&
    s.length > 0 &&
    s.length <= 256 &&
    s.trim() === s &&
    !/\p{Cc}/u.test(s);
  const message = (s: unknown): s is string =>
    typeof s === 'string' && s.length > 0 && s.length <= 1024;
  if (
    v['ok'] === true &&
    id(v['voice']) &&
    (v['warning'] === undefined || message(v['warning']))
  )
    return {
      ok: true,
      voice: v['voice'],
      ...(v['warning'] ? { warning: v['warning'] as string } : {}),
    };
  if (
    v['ok'] === false &&
    message(v['error']) &&
    (v['createdVoice'] === undefined || id(v['createdVoice']))
  )
    return {
      ok: false,
      error: v['error'],
      ...(v['createdVoice']
        ? { createdVoice: v['createdVoice'] as string }
        : {}),
    };
  return undefined;
}

/** Admit only the canonical mono PCM16 WAV generated by the Host. */
export function voiceSampleSeconds(bytes: Uint8Array): number | undefined {
  if (bytes.byteLength < 44 || bytes.byteLength > VOICE_SAMPLE_MAX_BYTES)
    return undefined;
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  const tag = (offset: number, value: string) =>
    [...value].every((c, i) => bytes[offset + i] === c.charCodeAt(0));
  if (
    !tag(0, 'RIFF') ||
    !tag(8, 'WAVE') ||
    !tag(12, 'fmt ') ||
    !tag(36, 'data') ||
    view.getUint32(4, true) !== bytes.byteLength - 8 ||
    view.getUint32(16, true) !== 16 ||
    view.getUint16(20, true) !== 1 ||
    view.getUint16(22, true) !== 1 ||
    view.getUint32(24, true) !== VOICE_SAMPLE_RATE ||
    view.getUint32(28, true) !== VOICE_SAMPLE_RATE * 2 ||
    view.getUint16(32, true) !== 2 ||
    view.getUint16(34, true) !== 16 ||
    view.getUint32(40, true) !== bytes.byteLength - 44 ||
    (bytes.byteLength - 44) % 2
  )
    return undefined;
  const seconds = (bytes.byteLength - 44) / (VOICE_SAMPLE_RATE * 2);
  return seconds >= VOICE_SAMPLE_MIN_SECONDS ? seconds : undefined;
}

export function encodeVoiceSample(samples: Float32Array): Uint8Array {
  const bytes = new Uint8Array(44 + samples.length * 2);
  const view = new DataView(bytes.buffer);
  const tag = (offset: number, value: string) =>
    [...value].forEach((c, i) => {
      bytes[offset + i] = c.charCodeAt(0);
    });
  tag(0, 'RIFF');
  view.setUint32(4, bytes.length - 8, true);
  tag(8, 'WAVE');
  tag(12, 'fmt ');
  view.setUint32(16, 16, true);
  view.setUint16(20, 1, true);
  view.setUint16(22, 1, true);
  view.setUint32(24, VOICE_SAMPLE_RATE, true);
  view.setUint32(28, VOICE_SAMPLE_RATE * 2, true);
  view.setUint16(32, 2, true);
  view.setUint16(34, 16, true);
  tag(36, 'data');
  view.setUint32(40, samples.length * 2, true);
  samples.forEach((sample, i) => {
    const value = Number.isFinite(sample)
      ? Math.max(-1, Math.min(1, sample))
      : 0;
    view.setInt16(
      44 + i * 2,
      Math.round(value * (value < 0 ? 32768 : 32767)),
      true,
    );
  });
  return bytes;
}
