/**
 * @license
 * Copyright 2026 Qwen
 * SPDX-License-Identifier: Apache-2.0
 */

import type { LiveLanguage } from '../i18n/messages.js';

/**
 * Notification language comes only from real user transcripts, never search
 * queries generated by the model, quoted web evidence, or backend reports.
 * Keep this outside a transport so reconnection cannot reset it to the UI.
 */
export class ConversationLanguage {
  private current?: LiveLanguage;
  private preference?: LiveLanguage;

  observeUserTranscript(transcript: string): void {
    const text = transcript.trim();
    if (!text) return;
    // Only standalone language requests count as a preference. A request to
    // translate a document or a quotation mentioning English is not one.
    const preference = text.match(
      /^(?:请|麻烦)?(?:以后|接下来|今后)?(?:请)?(?:一直|都)?(?:用|使用|改用|切换(?:成|为|到)?|改成|改为)(中文|简体中文|汉语|英文|英语)(?:和我(?:交流|说话|聊天)|(?:来)?(?:回答|回复|交流|说话|聊天))?(?:就好|好吗|可以吗)?[。！？.!?]*$/u,
    );
    const englishPreference = text.match(
      /^(?:please\s+)?(?:(?:respond|reply|answer|speak|talk)(?:\s+to\s+me)?\s+(?:in|using)|(?:switch|change)(?:\s+back)?\s+to|use)\s+(simplified\s+chinese|chinese|mandarin|english)(?:\s+from\s+now\s+on|\s+for\s+(?:your\s+)?(?:replies|responses|answers))?[.!?]*$/iu,
    );
    const requested = preference?.[1] ?? englishPreference?.[1];
    if (requested) {
      this.preference = /^(?:英文|英语|english)$/iu.test(requested)
        ? 'en'
        : 'zh-CN';
      this.current = this.preference;
      return;
    }
    if (this.preference) return;
    // Technical literals and short acknowledgements do not change the
    // conversational language (e.g. a Chinese user's "OK" or a Git URL).
    const prose = text
      .replace(/```[\s\S]*?```|`[^`]*`/gu, ' ')
      .replace(/https?:\/\/\S+|\bwww\.\S+/giu, ' ')
      .replace(/(?:^|\s)(?:~?\/|[A-Za-z]:\\)\S+/gu, ' ')
      .trim();
    if (
      /^(?:ok(?:ay)?|yes|no|yep|nope|sure|thanks?|thank you|go ahead|好的?|可以|行|嗯|是的?|不是|谢谢)[\s。！？.!?]*$/iu.test(
        prose,
      ) ||
      /^(?:git|npm|npx|pnpm|yarn|node|python\d*|cd|ls|pwd|cat|rg|curl|wget|ssh|sudo)\s/iu.test(
        prose,
      )
    )
      return;
    if ((prose.match(/\p{Script=Han}/gu)?.length ?? 0) >= 2) {
      this.current = 'zh-CN';
    } else if (
      !/[\p{Script=Hiragana}\p{Script=Katakana}\p{Script=Hangul}\p{Script=Cyrillic}\p{Script=Arabic}]/u.test(
        prose,
      ) &&
      (prose.match(/\b[A-Za-z]+(?:'[A-Za-z]+)?\b/gu)?.length ?? 0) >= 3
    ) {
      this.current = 'en';
    }
  }

  resolve(fallback: LiveLanguage): LiveLanguage {
    return this.current ?? fallback;
  }
}
